import {
    Avatar,
    Button,
    Cascader,
    Col,
    DatePicker,
    Divider,
    Dropdown,
    Form,
    FormModel,
    Icon,
    Input,
    InputNumber,
    Layout,
    Menu,
    Modal,
    message,
    Popconfirm,
    Radio,
    Row,
    Select,
    Spin,
    Steps,
    Table,
    Tooltip,
    Tree,
    TreeSelect,
    Timeline,
    Upload,
    Drawer,
    Empty,
    Pagination,
    Checkbox,
    List,
    Card,
    Tag,
    Progress,
    Popover,
    Tabs,
    Transfer,
    Switch,
    Badge,
    TimePicker,
    ConfigProvider,
    Space,
    Carousel,
    Slider
  } from "ant-design-vue";
  const components = {
    Avatar,
    Button,
    Cascader,
    Col,
    DatePicker,
    Divider,
    Dropdown,
    Form,
    FormModel,
    Icon,
    Input,
    InputNumber,
    Layout,
    Menu,
    Modal,
    message,
    Popconfirm,
    Radio,
    Row,
    Select,
    Spin,
    Steps,
    Table,
    Tooltip,
    Tree,
    TreeSelect,
    Timeline,
    Upload,
    Drawer,
    Empty,
    Pagination,
    Checkbox,
    List,
    Card,
    Tag,
    Progress,
    Popover,
    Tabs,
    Transfer,
    Switch,
    Badge,
    TimePicker,
    ConfigProvider,
    Space,
    Carousel,
    Slider
  };
  
  export default Vue => {
    Object.keys(components).forEach(key => Vue.use(components[key]));
    // Vue.component('VueCropper',VueCropper);
    Vue.prototype.$message = message;
    Vue.prototype.$info = Modal.info;
    Vue.prototype.$success = Modal.success;
    Vue.prototype.$error = Modal.error;
    Vue.prototype.$warning = Modal.warning;
    Vue.prototype.$destroyAll = Modal.destroyAll;
  };
  